In [3]:
print("Hello, jupyter!")

Hello, jupyter!


In [4]:
# установка NumPy
!pip install numpy

In [8]:
# импортирование модуля (библиотеками, фреймворки)
import numpy as np 

- создание массивов

In [10]:
# создание вектор-строку(1-мерный массив)
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [12]:
np.array(my_list)

array([1, 2, 3, 4, 5])

In [14]:
# создание (вектор-строки) из нулей
z = np.zeros(10)
z 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
# создание вектор-столбца из нулей
# (кол-во строк, кол-во столбцов)
np.zeros((3,1))

array([[0.],
       [0.],
       [0.]])

In [18]:
# создание матрицы из нулей
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
# метод который создает вектор-строку со значениями из линейной последовательности
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(10, 100, 5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [32]:
# вектор-строка со значениями из равномерного распределения
# например, от 0 до 1
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [35]:
np.linspace(1, 100, 5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [72]:
# случайные значения из равномерного распределение от 0 до 1
np.random.randint(5)

1

In [43]:
# случайные целые значения
# случайное число от 0 до 10
np.random.randint((10))

4

In [46]:
# вектор-строка со знач. от 0 до 10 размером (длиной) 5
np.random.randint(10, size=5)

array([3, 0, 6, 4, 4])

In [80]:
# матрица формой 2 на 3 со случ. знач. от 10 до 20
np.random.randint(10, 20, size=(2,3)) 

array([[13, 13, 19],
       [19, 14, 11]])

In [83]:
- атрибуты 

NameError: name 'атрибуты' is not defined

In [55]:
a = np.random.randint(10, size=(3,5))
a

array([[1, 0, 9, 4, 0],
       [9, 0, 9, 5, 8],
       [5, 7, 0, 8, 0]])

In [57]:
# размерность массива - кол-во измерений/осей
a.ndim

2

In [76]:
# форма массива
a.shape

(3, 5)

In [78]:
# кол-во всех элементов массива
a.size 

15

In [82]:
# тип значений массива 
a.dtype

dtype('int32')

In [86]:
a.astype("float16")

array([[1., 0., 9., 4., 0.],
       [9., 0., 9., 5., 8.],
       [5., 7., 0., 8., 0.]], dtype=float16)